; PlatformIO Project Configuration File

; PlatformIO Project Configuration File

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; --- Memory & Partition Configuration for 16MB Flash / 8MB PSRAM ---
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

; Library dependencies
lib_deps =
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.5
    makuna/RTC@^2.5.0
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.3
    https://github.com/gravitech-engineer/AIS_IoT_4G.git

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM              ; Enable the 8MB PSRAM
    
    ; --- USB Serial Configuration ---
    ; If your S3 board uses the Native USB port for programming/serial monitor, set this to 1.
    ; If it has a dedicated CP2102/CH340 chip for UART, set this to 0.
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1